# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://rausial.github.io/bear_voila/"

git_url = "https://github.com/rausial/bear_voila/tree/master/"

def custom_doc_links(name): return None
